dev_mode: false
num_pots: 60
seven_segment_type: common_cathode  # or common_anode
segment_pins:
  digit1:
    a: FIO4
    b: FIO5
    c: FIO6
    d: FIO7
    e: EIO0
    f: EIO1
    g: EIO2
  digit2:
    a: EIO0
    b: EIO1
    c: EIO2
    d: EIO3
    e: FIO7
    f: EIO4
    g: EIO5
binary_pins:
  digit1:
    bit0: FIO4
    bit1: FIO5
    bit2: FIO6
    bit3: FIO7
  digit2:
    bit0: EIO0
    bit1: EIO1
    bit2: EIO2
    bit3: EIO3
relay_pins:
  forward: DAC0
  reverse: DAC1
timeout_seconds: 60